### ISSUE TITLE
Const-correctness?

### ISSUE THREAD

**Issue by milasudril** [erikd/libsamplerate#18]
Is this OK:

    SRC_DATA data{};
    data.data_in=const_cast<float*>(buffer_in);

That is, can I be sure that the library does not touch buffer_in? If so add `const`, or at least annotate that in the documentation.

**Comment by erikd** [comment]
https://github.com/erikd/libsamplerate/blob/master/src/samplerate.h#L27

**Comment by milasudril** [comment]
Good to know. This was not in the Xenial include file. Also the docs need to be updated.

**Comment by erikd** [comment]
> Also the docs need to be updated.

PR would be appreciated.

**Comment by erikd** [comment]
This has been fixed. Closing.
