### ISSUE TITLE
examples/audio_out.c fails on newer MacOS

### ISSUE THREAD

**Issue by janstary** [erikd/libsamplerate#28]
`examples/audio_out.c` fails to build on MacOS 10.13.2,
because it includes `Carbon.h` which does not exist.
Apparently, the MacOS audio subsystem has changed again
(to proactively leverage the synergy of the frameworks).

**Comment by janstary** [comment]
Currently, the MacOS port just does not build the examples.
https://github.com/macports/macports-ports/blob/master/audio/libsamplerate/files/patch_examples_Makefile.in.diff

**Comment by erikd** [comment]
I am well aware  of this. I don't use Mac OS X so someone else needs to write this.

**Comment by jmroot** [comment]
First problem by inspection is AudioHardwareGetProperty, which went away after 10.6. Migration guide here: https://developer.apple.com/library/content/technotes/tn2223/_index.html

**Comment by conradjones** [comment]
pull request https://github.com/erikd/libsamplerate/pull/53

**Comment by erikd** [comment]
Fix has been merged. Closing this. Thanks!
