### ISSUE TITLE
fftw3 not found

### ISSUE THREAD

**Issue by janstary** [erikd/libsamplerate#31]
./configure does not find fftw3, because configure.ac wants
`PKG_CHECK_MODULES(FFTW3, fftw3 >= 0.15.0, ac_cv_fftw3=1, ac_cv_fftw3=0)`

What is `0.15.0` of fftw3? It installs fftw 3.x.y, obviously.

Why do we require a certain version in the first place?

**Comment by janstary** [comment]
Ah, this is 0.1.9. The current git seems to find it.
But still: why is the 0.15.0 there? Why not require just `fftw3`?

**Comment by erikd** [comment]
> What is 0.15.0 of fftw3? 

Cruft left over from earlier times.

> Why do we require a certain version in the first place?

In case we need a certain minimum version.
