### ISSUE TITLE
Speed question

### ISSUE THREAD

**Issue by eblanca** [erikd/libsamplerate#4]
Are you considering for libsamplerate use of hardware instructions we can find in modern processors (SIMD) / GPUs? This can greatly affect the speed of resampling.
Will this impact on library precision?

**Comment by erikd** [comment]
Both I, and someone more experienced than I have attempted to recode this algorithm in SIMD instructions. Unfortunately, due to the intricacies of the said algorithm, the SIMD performance was not faster than the C code.

**Comment by eblanca** [comment]
Thank you Erik.
