### ISSUE TITLE
export SRC_STATE size?

### ISSUE THREAD

**Issue by elaforge** [erikd/libsamplerate#40]
I'd like to save and restore SRC_STATE, so I can rerender a resampled output incrementally.  For this, I think I just need to know the size of SRC_STATE, then I can use memcpy to serialize and deserialize.  So I think a new src_size method is needed.  But I could use that to redo src_clone, from commit 945b9939d296c939385fbecfc762c4c335f73dfe, in a generic way and get rid of those individual *_copy functions.

Any interest in a PR?  Or is this already possible?

**Comment by erikd** [comment]
This idea requires that the data pointed to by the `SRC_STATE` pointer is contiguous. I'm not sure if that is the case now (haven't checked) and even if is is contiguous now, there is no reason why that would always be so.

So I'm curious, why? Are you going to save the `SRC_STATE` to disk or send it over a network?

**Comment by elaforge** [comment]
Oh you're right, there's a void* in there.  Ok, I can't simplify src_clone() after all.  I guess it could be saved in two chunks though.  Maybe return struct { size_t size1, size2, void *state1, *state2 }.  Or if that's too hard-coded, I could allocate a big chunk, as long as it's ok to malloc.

Why is that I'm using it for a sampler in Haskell.  I want to be able to incrementally rerender only the changed part of the score, which I plan to do by saving the state at regular intervals so I can restart there.  So saving to disk, but no network, and doesn't need to be portable.

**Comment by erikd** [comment]
Honestly, I don't think this is something I'd like to add to the public API. This idea of yours leaks internal state and make previously opaque internal state transparent. That means that when the internal change I have to bump the API and ABI version numbers.

I'm also wondering what this actually saves you. On modern CPUs, the converter is really fast and disk space is super cheap. Isn't it possible to just cache the sample rate conversion output on disk?

**Comment by elaforge** [comment]
I hope it wouldn't cause API changes... I guess you mean a new library version would invalidate opaque binary blobs written by a previous one, but it's just a cache so I wouldn't be fussed if every library version change did that.  But I'm also ok with pinning the version and making a fork, and maybe it's actually best to start that way, because I'm not totally sure my approach will work.  I'm also happy to depend on private API, but I guess the private structs would have to go in their own headers at least.  So I'll do a local fork for the moment.  If it does work out hopefully in the future I can show you something more compelling :)

I am planning to cache sample rate conversion output, that's the idea.  What I'm trying to do is only rerender the changed bit, to avoid starting from the beginning each time.  It's the same idea as incremental recompilation.  It's true that resampling is cheap, but I have noticed that one minute of one audio channel at high quality will take a second or so, which is at the threshold of too slow.  Assuming a realistic maximum of 30 minutes of several hundred channels, I'm assuming even low quality won't be able to complete in a second or so, just based on IO alone.  In fact I guess traditional realtime sampling is all IO-bound nowadays, so once you install an SSD, the fast CPU doesn't help much.  Oh and other things, like time stretching and convolution, definitely are CPU bound, and it would be nice to fit everything into the same incremental framework.
