### ISSUE TITLE
Duplicate frame in output with src_ratio = 1.0

### ISSUE THREAD

**Issue by monocasual** [erikd/libsamplerate#44]
I have a simple array of floats containing a sequence of numbers such as `1.0, 2.0, 3.0, ... 64.0` I want to process through libsamplerate. Surprisingly, when the ratio is set to 1.0, the first frame in the output buffer is duplicated, that is `1.0, 1.0, 2.0, 3.0, ...` instead of the expected `1.0, 2.0, 3.0, 4.0, ...`. 

I'm using libsamplerate 0.1.9 on Debian Stretch, GCC 6.3.0 (64 bit arch). I'm pretty sure there is something wrong on my side, even if I have triple checked it so far. Or maybe it is the expected behavior? Full code below:

```
#include <samplerate.h>
#include <cstdio>


int main()
{
	SRC_STATE* rsmp_state;
	SRC_DATA   rsmp_data;

	const int IN_FRAMES  = 64;
	const int OUT_FRAMES = 32;

	float* in  = new float[IN_FRAMES];
	float* out = new float[OUT_FRAMES];

	for (int i = 0; i < IN_FRAMES; i++)
		in[i] = (float) i + 1;

	rsmp_state = src_new(SRC_LINEAR, 1, nullptr);

	rsmp_data.data_in       = in; 
	rsmp_data.input_frames  = IN_FRAMES; 
	rsmp_data.data_out      = out; 
	rsmp_data.output_frames = OUT_FRAMES;
	rsmp_data.end_of_input  = false;
	rsmp_data.src_ratio     = 1.0;

	src_process(rsmp_state, &rsmp_data);

	//for (int i = 0; i < IN_FRAMES; i++)  printf("%d) %f\n", i, in[i]);
	for (int i = 0; i < OUT_FRAMES; i++) printf("%d) %f\n", i, out[i]);

	src_delete(rsmp_state);
	delete in;
	delete out;
}
```

**Comment by erikd** [comment]
libsamplerate was designed to be used on what is effectively an infinite stream of input samples. What happens at the start and the end of a finite block of samples should not be relied on.
