### ISSUE TITLE
Make CMake tests and install directives optional

### ISSUE THREAD

**Issue by robiwano** [erikd/libsamplerate#46]
When using libsamplerate via CMake and as a submodule, all targets related to tests/examples clog up generated workspace. It should be make optional f.i. with:

`option(LIBSAMPLERATE_TESTS OFF "Enable to generate test targets)
`

Same applies to `install(...)` directives.

**Comment by erikd** [comment]
Building tests should be the default behavior.

**Comment by robiwano** [comment]
Sounds reasonable. It could be done like so:
```
if (${CMAKE_SOURCE_DIR} STREQUAL ${CMAKE_CURRENT_SOURCE_DIR})
  option(LIBSAMPLERATE_TESTS ON "Enable to generate test targets)
else()
  option(LIBSAMPLERATE_TESTS OFF "Enable to generate test targets)
endif()
```
Then for a standalone build, tests are enabled.

**Comment by erikd** [comment]
Well then, you should prepare a PR :)
