### ISSUE TITLE
Description of src_ratio field in api_misc section of the website is wrong

### ISSUE THREAD

**Issue by Ashymad** [erikd/libsamplerate#56]
From: http://www.mega-nerd.com/SRC/api_misc.html#SRC_DATA 
>Finally, the src_ratio field specifies the conversion ratio defined as the input sample rate divided by   the output sample rate.

While it should be "output sample rate divided by input sample rate". Elsewhere in the documentation it is specified correctly:
>src_ratio     : Equal to output_sample_rate / input_sample_rate.

**Comment by erikd** [comment]
Would be more than happy to get a patch for this.
