### ISSUE TITLE
failed to install libsamplerate

### ISSUE THREAD

**Issue by 13077847700** [erikd/libsamplerate#61]
brew install libsamplerate
curl: (7) Failed to connect to www.mega-nerd.com port 80: Operation timed out
Error: An exception occurred within a child process:
DownloadError: Failed to download resource "libsamplerate"
Download failed: http://www.mega-nerd.com/SRC/libsamplerate-0.1.9.tar.gz

**Comment by erikd** [comment]
The command:
```
curl http://www.mega-nerd.com/SRC/libsamplerate-0.1.9.tar.gz -o libsamplerate-0.1.9.tar.gz
```
works fine here and on a couple of remote machine I have access to.

If this does not work for you, the problem is local to your machine or network.
