### ISSUE TITLE
Win compilation error 

### ISSUE THREAD

**Issue by lwaldner** [erikd/libsamplerate#9]
When compiling on windows I get the following warning and errors:

.\examples\audio_out.c(715): warning C4133: 'return': incompatible types - from 'WIN32_AUDIO_OUT *' to 'AUDIO_OUT *'
.\examples\audio_out.c(826): error C2065: 'sample_count': undeclared identifier
.\examples\audio_out.c(827): error C2065: 'sample_count': undeclared identifier
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.exe"' : return code '0x2'

I looked that the lines of code in audio_out.c and couldn't find an obvious error. I think I may be missing some header file but can't figure it out.

**Comment by erikd** [comment]
@lwaldner Is that compiling from git or compiling from the release source tarball?

**Comment by DJMaster** [comment]
Please look at PR https://github.com/erikd/libsamplerate/pull/10
