### ISSUE TITLE
src_process fails to properly handle chunked input

### ISSUE THREAD

**Issue by Flamefire** [erikd/libsamplerate#90]
There is a bug when using src_process with sufficiently small chunks of input data. Although the result of passing the input data in chunks should be exactly the same as when passing them as 1 block the test shows that this is not the case and NO output is generated. See #87 for a reproducer.

This seems to be the issue that was discussed at https://github.com/erikd/libsamplerate/issues/55 but now can be reproduced using (IMO) valid code: It sets the `end_of_input` once it got the final samples but the `output_frames_gen` is still zero.

**Comment by erikd** [comment]
> sufficiently small chunks of input data

Libsamplerate is designed to be used for effectively infinite chunks of audio, eg many seconds and up. What happens on sub second chunks is irrelevant.
