### ISSUE TITLE
build instructions for ios

### ISSUE THREAD

**Issue by mlostekk** [erikd/libsamplerate#95]
Do you have a guide how to compile this as a fat library for all required ios architectures (x86_64, armv6, armv7, ...)?

**Comment by Katko** [comment]
Hey @mlostekk you can use `cmake`.

- `brew install cmake`
- navigate to the dir that you cloned `libsamplerate` 
- then follow the instructions here https://cmake.org/cmake/help/latest/manual/cmake-toolchains.7.html#cross-compiling-for-ios-tvos-or-watchos  ***OR*** make use of this repo https://github.com/leetal/ios-cmake which has already some predefined flags for different iOS Platforms for example the `-DPLATFORM=OS64COMBINED` will build a FAT library for Device & Simulator arch only for (x86_64, arm64). Regular `cmake` variables/flags/options can be used as well. Note that the flag mentioned as an example will not include `armv7...` or any older arch types.

**Comment by erikd** [comment]
Thanks @Katko !

**Comment by Katko** [comment]
Hey @erikd I was using GitHub repo mentioned above to build `libsamplerate` but I stumbled upon an issue with some unsigned code. I am sharing below the error message and the environment used. Looks like it is something coming from one of the test files in `libsamplerate` any ideas how to resolve it? 

### Error
```
Check dependencies
Code Signing Warning: "snr_bw_test" isn't code signed but requires entitlements. It is not possible to add entitlements to a binary without signing it.
Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 12.4'

** BUILD FAILED **
```

### Environment
`cmake version 3.15.2`
`Xcode 10.3`

**Comment by erikd** [comment]
`snr_bw_test` is a program in the test suite. I know nothing about iOS dev.
